services:
  - type: web
    name: employee-verification-portal
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python manage.py migrate && gunicorn employee_portal.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: DJANGO_SETTINGS_MODULE
        value: employee_portal.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: True
      - key: ALLOWED_HOSTS
        value: employee-verification-portal.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: employee-portal-db
          property: connectionString
    plan: free
    disk:
      name: employee-portal-disk
      mountPath: /opt/render/project/src/media
      sizeGB: 1

databases:
  - name: employee-portal-db
    databaseName: employee_portal
    user: employee_portal_user
    plan: free 