# Generated by Django 5.0.2 on 2025-04-23 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0006_usergroup_groupmember_competency'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmember',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to='admin_portal.employee'),
        ),
    ]
