# Generated by Django 5.0.2 on 2025-05-03 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0007_groupmember_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='competency',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='competencies', to='admin_portal.groupmember'),
        ),
    ]
