# Generated by Django 5.0.2 on 2025-05-03 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0008_competency_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competency',
            name='member',
        ),
        migrations.AddField(
            model_name='groupmember',
            name='competencies',
            field=models.ManyToManyField(blank=True, related_name='members', to='admin_portal.competency'),
        ),
    ]
