# Generated by Django 5.2.1 on 2025-05-11 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0014_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='custom_theme_color',
            field=models.CharField(default='#000000', help_text='Custom theme color in hex format (e.g., #000000)', max_length=7),
        ),
    ]
